import { PERMISSIONS } from '@constants/permissions.constants';

export const STUDENT_PERMISSIONS = {
  STUDENT_READ: PERMISSIONS.STUDENT_READ,
  STUDENT_READ_BASIC: PERMISSIONS.STUDENT_READ_BASIC,
  STUDENT_CREATE: PERMISSIONS.STUDENT_CREATE,
  STUDENT_UPDATE: PERMISSIONS.STUDENT_UPDATE,
  STUDENT_DELETE: PERMISSIONS.STUDENT_DELETE,
  STUDENT_TRANSFER: PERMISSIONS.STUDENT_TRANSFER,
  STUDENT_ASSIGN_SEAT: PERMISSIONS.STUDENT_ASSIGN_SEAT,
} as const;
