/** Billing cycle stored on LibrarySubscription (includes trial). */
export const SUBSCRIPTION_RECORD_BILLING_CYCLE = {
  TRIAL: 'TRIAL',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
  CUSTOM: 'CUSTOM',
} as const;
export type SubscriptionRecordBillingCycle =
  (typeof SUBSCRIPTION_RECORD_BILLING_CYCLE)[keyof typeof SUBSCRIPTION_RECORD_BILLING_CYCLE];

/** Canonical subscription entitlement status. */
export const SUBSCRIPTION_RECORD_STATUS = {
  TRIALING: 'TRIALING',
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  EXPIRED: 'EXPIRED',
  SUSPENDED: 'SUSPENDED',
  CANCELLED: 'CANCELLED',
} as const;
export type SubscriptionRecordStatus =
  (typeof SUBSCRIPTION_RECORD_STATUS)[keyof typeof SUBSCRIPTION_RECORD_STATUS];

export const SUBSCRIPTION_EVENT_TYPE = {
  TRIAL_STARTED: 'TRIAL_STARTED',
  TRIAL_EXTENDED: 'TRIAL_EXTENDED',
  INVOICE_CREATED: 'INVOICE_CREATED',
  PAYMENT_COLLECTED: 'PAYMENT_COLLECTED',
  PLAN_UPGRADED: 'PLAN_UPGRADED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_SCHEDULED: 'SUBSCRIPTION_SCHEDULED',
  SUBSCRIPTION_ADJUSTED: 'SUBSCRIPTION_ADJUSTED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_ACTIVATED: 'TENANT_ACTIVATED',
  SUBSCRIPTION_SYNCED: 'SUBSCRIPTION_SYNCED',
} as const;
export type SubscriptionEventType =
  (typeof SUBSCRIPTION_EVENT_TYPE)[keyof typeof SUBSCRIPTION_EVENT_TYPE];

export const SUBSCRIPTION_AUDIT_ACTION = {
  SUBSCRIPTION_ADJUST: 'SUBSCRIPTION_ADJUST',
  SUBSCRIPTION_EXTEND_TRIAL: 'SUBSCRIPTION_EXTEND_TRIAL',
  SUBSCRIPTION_SYNC: 'SUBSCRIPTION_SYNC',
} as const;
